const { post } = require("../routes");

const emails = [
    'raham.demetris@aufderhar.com',
    'trolfson@schmeler.com',
    'holly27@yahoo.com',
    'hbecker@yahoo.com',
    'nolan.waelchi@hotmail.com',
    'lilly11@beier.org',
    'chyatt@lockman.com',
    'wilma45@yahoo.com',
    'collin.kub@feest.biz',
    'vonrueden.concepcion@gmail.com',
    'lexus52@spencer.biz',
    'rubie42@bogisich.com',
    'larkin.waylon@schamberger.com',
    'legros.jermey@johnston.com',
    'snienow@batz.com',
    'cummerata.jamar@yahoo.com',
    'waters.otilia@hane.com',
    'vicente02@yahoo.com',
    'karina.bruen@yahoo.com',
    'angelica.schmitt@ryan.biz',
    'mariah.bradtke@anderson.com',
    'ljohnson@shanahan.org',
    'hammes.duane@yahoo.com',
    'graciela04@swaniawski.com',
    'jwintheiser@hotmail.com',
    'sawayn.landen@yahoo.com',
    'kaitlyn.denesik@williamson.com',
    'emmy01@glover.biz',
    'shanel.deckow@bechtelar.com',
    'lakin.mara@pacocha.info',
    'morris42@gmail.com',
    'brennon10@zieme.com',
    'madge11@yahoo.com',
    'awehner@tromp.net',
    'clementina.gutmann@jaskolski.com',
    'helene.schuster@mclaughlin.biz',
    'quigley.jolie@hotmail.com',
    'howell.novella@schroeder.org',
    'fbrown@yahoo.com',
    'raoul.carroll@yahoo.com',
    'klocko.bertram@maggio.biz',
    'wjacobson@pacocha.net',
    'richie.mertz@cole.com',
    'ewell21@kessler.com',
    'monserrate84@robel.org',
    'xrath@gmail.com',
    'cathryn.welch@will.info',
    'pcarter@weissnat.net',
    'phodkiewicz@yahoo.com',
    'jade14@gmail.com',
    'dariana58@gmail.com',
    'smarquardt@weber.info',
    'zena.gulgowski@hotmail.com',
    'toney96@gibson.com',
    'zrosenbaum@hotmail.com',
    'nona00@mcdermott.com',
    'bosco.velda@hotmail.com',
    'christian27@morar.info',
    'blanda.jeramy@hotmail.com',
    'fadel.dudley@ebert.com',
    'predovic.ilene@feeney.com',
    'charlotte.rau@grant.org',
    'williamson.augustus@moen.biz',
    'fpaucek@hermiston.org',
    'mmccullough@bartoletti.biz',
    'ubauch@gmail.com',
    'satterfield.katherine@gutkowski.com',
    'weissnat.vickie@gmail.com',
    'feest.cristal@rutherford.com',
    'mae.murazik@howe.info',
    'oscar.lynch@yahoo.com',
    'luciano.lind@wisozk.com',
    'treutel.shannon@wiegand.org',
    'crystel38@hotmail.com',
    'randi.damore@hintz.com',
    'corrine82@gmail.com',
    'violette31@hotmail.com',
    'sim.corkery@yahoo.com',
    'brennan01@yahoo.com',
    'erdman.genesis@hotmail.com',
				
];

const usernames = [
    'Rebarbative',
    'Rookery',
    'Mastoid',
    'Balderdash',
    'Thingamabob',
    'Shituation',
    'RyangarFiasco',
    'Angiosperm',
    'LatretKoto',
    'Pussyfoot',
    'Habilitate',
    'Bifurcate',
    'Monorhyme',
    'XxherodBungey',
    'Pileated',
    'Arda_7Guru',
    'Erythropsia',
    'Popinjay',
    'Passant',
    'Hotfoot',
    'That1738queeRecto',
    'Yellowbelly',
    'Scapigerous',
    'Manscape',
    'Plangency',
    'Bia_Nabob',
    'Angelology',
    'Rambunctious',
    'Kritarchy',
    'JefwilBonny',
    'MaggotyLimes',
    'ChubbylilMiasma',
    'Vaccine',
    'Hoydenism',
    'Phaeton',
    'Fartkontrol',
    'Paraesthesia',
    'Eavesdrop',
    'K1llertacEffete',
    'Mucketymuck',
    'Wanzex375',
    'Hebdomadally',
    'Luteous',
    'Svengali',
    'Bippybuddy11',
    'Igloo',
    'Ornithoscopy',
    'Goombah',
    'Vermiculated',
    'Sprinkles',
    'Veracity',
    'Fizz',
    'Cubomancy',
    'Unau',
    'Pneumatic',
    'Majordomo',
    'Cocarde',
    'Amok',
    'Zuchelesmc',
    'Hambone',
    'Ruiniferous',
    'Hocuspocus',
    'Glenoid',
    'Boondoggle',
    'Remotion',
    'Bugbear',
    'Gyrusruzzyh2',
    'Fricassee',
    'Houselthar69',
    'Durst',
    'Spinosity',
    'Furbelows',
    'Bongoci1000',
    'Schluffy',
    'Vallation',
    'Sojourn',
    'Polydipsia',
    'Ausfahrt',
    'Vengeance',
    'Fuggy',

]

const passwords = [
    'vHBBwR9K',
    'Skg5V8RK',
    '8za9fWpB',
    'WZVmU394',
    'SHSWwcyE',
    'FWAgbqzN',
    'ykAcVMtv',
    '4aKr5SP6',
    'm8smd5Th',
    'uMBucyrD',
    'a7HFvrXH',
    '9pw4L5qV',
    'FAcCjAaM',
    'P36XQfLE',
    'Acr4qkQK',
    'D2wS8S5p',
    'zwTVujm2',
    'vZntRJmA',
    'UKHsXWr4',
    '2pmFnBHc',
    'yCKb2FK3',
    'wSksHCKm',
    'qgBHmx9v',
    'RTpygyVu',
    'j5zHbx3K',
    '6EhMpJVM',
    'pZeS3FNu',
    'mmmSWKgx',
    'Vgnf82Jc',
    'ZKzhptWZ',
    'c3xLetCp',
    '9BxMyAvh',
    'CufZFV62',
    'JnCMHbzQ',
    '6Ka4a6sL',
    '6D7jUH9u',
    'LzbUd3hG',
    'Zbe3FPxG',
    'jKBA3AJa',
    'Cf7UeFBB',
    'DsUjtr25',
    'JX2SVJw2',
    'QAe9PL3c',
    'yzYyRb5z',
    '6cbvYrAW',
    'AqnsGg56',
    'QYnxBu9T',
    'c42FBckJ',
    'xXQLEvrW',
    'WbTV6SxW',
    'XaVUQH83',
    'QY36C6Z8',
    '7xWAVGj3',
    'pQCVJg3X',
    'p6pBChmt',
    '3TxF3xe9',
    '42SgTbb3',
    'P8gCsZuZ',
    'gSNhHnUH',
    'WrAqXkvB',
    'cvvMhyAt',
    's4frSenp',
    'Z83Ymsed',
    'Z2hmm7Gy',
    'gA94f8k6',
    'Xjawm9yc',
    'tk2zGN3X',
    '2L7xCSZW',
    'Yg3AwhR7',
    'cbpncQtL',
    'qSbNnGS6',
    '5VsRfCkQ',
    '663VSgHF',
    'xWhqZu9A',
    'UZHPqdbb',
    'f3t7naj7',
    'uuSkdfcH',
    'DkzgDT9P',
    'bBD4qMkS',
    'MH64MCXm',
]
const posts =[
    'what up with this stuff?',
    'who knows where to find...',
    "I'm afraid of cows",
    "whats going on in town?",
    "TIL english is a dumb language... silent letters smh",
    "I hate clowns!",
    "best concert ever!",
    "never look a street cat in the eye",
    "who won the peloponessian war? Sparta?",
    "I just bought a lottery ticket, wish me luck",
    "I broke my leg climbing a tree",
    "turtles are cool",
    "The MCU is going downhill..."
]

const getRadomArrItem = (arr) => arr[Math.floor(Math.random() * arr.length)];

const getRandomEmail = () =>
    `${getRadomArrItem(emails)}`;

const getRandomUsername = () => 
    `${getRadomArrItem(usernames)}`;

const getRandomPost = () => 
    `${getRadomArrItem(posts)}`;

const getRandomPassword = () => 
    `${getRadomArrItem(passwords)}`
    

module.exports = {getRandomEmail, getRandomUsername, getRandomPost, getRandomPassword};
